//! Bulk operations for IntegrationConnector entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateIntegrationConnectorDto;
use crate::application::service::IntegrationConnectorService;
use crate::domain::entity::IntegrationConnector;

/// Bulk operation handler for IntegrationConnector entities.
///
/// Wraps `IntegrationConnectorService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type IntegrationConnectorBulkService = GenericBulkService<IntegrationConnector, CreateIntegrationConnectorDto, IntegrationConnectorService>;

// <<< CUSTOM
// END CUSTOM
