//! Bulk operations for IntegrationEvent entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateIntegrationEventDto;
use crate::application::service::IntegrationEventService;
use crate::domain::entity::IntegrationEvent;

/// Bulk operation handler for IntegrationEvent entities.
///
/// Wraps `IntegrationEventService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type IntegrationEventBulkService = GenericBulkService<IntegrationEvent, CreateIntegrationEventDto, IntegrationEventService>;

// <<< CUSTOM
// END CUSTOM
