//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod integration_connector_bulk;
pub mod integration_event_bulk;

pub use integration_connector_bulk::IntegrationConnectorBulkService;
pub use integration_event_bulk::IntegrationEventBulkService;

// <<< CUSTOM
// END CUSTOM
