//! IntegrationConnector DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::IntegrationConnector;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ConnectorDirection;
use crate::domain::entity::ConnectorKind;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new IntegrationConnector
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateIntegrationConnectorDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub provider: String,
    pub kind: ConnectorKind,
    pub direction: ConnectorDirection,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a IntegrationConnector
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateIntegrationConnectorDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub provider: String,
    pub kind: ConnectorKind,
    pub direction: ConnectorDirection,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a IntegrationConnector
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchIntegrationConnectorDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<ConnectorKind>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub direction: Option<ConnectorDirection>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchIntegrationConnectorDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.provider.is_some() || self.kind.is_some() || self.direction.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for IntegrationConnector entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct IntegrationConnectorResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub provider: String,
    pub kind: ConnectorKind,
    pub direction: ConnectorDirection,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for IntegrationConnector entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct IntegrationConnectorListResponseDto {
    /// List of items
    pub items: Vec<IntegrationConnectorResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl IntegrationConnectorListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<IntegrationConnectorResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct IntegrationConnectorSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub provider: String,
    pub kind: ConnectorKind,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<IntegrationConnector> for IntegrationConnectorResponseDto {
    fn from(entity: IntegrationConnector) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            provider: entity.provider,
            kind: entity.kind,
            direction: entity.direction,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<IntegrationConnector> for IntegrationConnectorSummaryDto {
    fn from(entity: IntegrationConnector) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            provider: entity.provider,
            kind: entity.kind,
            created_at,
        }
    }
}

impl From<CreateIntegrationConnectorDto> for IntegrationConnector {
    fn from(dto: CreateIntegrationConnectorDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            provider: dto.provider,
            kind: dto.kind,
            direction: dto.direction,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&IntegrationConnector> for IntegrationConnectorResponseDto {
    fn from(entity: &IntegrationConnector) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            provider: entity.provider.clone(),
            kind: entity.kind.clone(),
            direction: entity.direction.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateIntegrationConnectorDto> for IntegrationConnector {
    fn from_create_dto(dto: CreateIntegrationConnectorDto) -> backbone_core::ServiceResult<Self> {
        Ok(IntegrationConnector::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateIntegrationConnectorDto> for IntegrationConnector {
    fn apply_update(mut self, dto: UpdateIntegrationConnectorDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.provider = dto.provider;
        self.kind = dto.kind;
        self.direction = dto.direction;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to IntegrationConnector here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

