//! Domain policy for IntegrationEvent aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::IntegrationEvent;

/// Domain policy for IntegrationEvent — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<IntegrationEvent>` in the `// <<< CUSTOM` zone.
pub type IntegrationEventDomainPolicy = PermitAllPolicy<IntegrationEvent>;

// <<< CUSTOM
// END CUSTOM
