//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod integration_connector_domain_policy;
pub mod integration_event_domain_policy;

pub use integration_connector_domain_policy::IntegrationConnectorDomainPolicy;
pub use integration_event_domain_policy::IntegrationEventDomainPolicy;

// <<< CUSTOM
// END CUSTOM
