//! Application service for IntegrationAccount entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `integration_account_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateIntegrationAccountDto, UpdateIntegrationAccountDto};
use crate::domain::entity::IntegrationAccount;
use crate::infrastructure::persistence::IntegrationAccountRepository;

/// Application service for IntegrationAccount entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `integration_account_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct IntegrationAccountServiceCustom {
///     inner: Arc<IntegrationAccountService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type IntegrationAccountService = GenericCrudService<
    IntegrationAccount,
    CreateIntegrationAccountDto,
    UpdateIntegrationAccountDto,
    IntegrationAccountRepository,
>;

// <<< CUSTOM
// END CUSTOM
