//! Application service for IntegrationConnector entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `integration_connector_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateIntegrationConnectorDto, UpdateIntegrationConnectorDto};
use crate::domain::entity::IntegrationConnector;
use crate::infrastructure::persistence::IntegrationConnectorRepository;

/// Application service for IntegrationConnector entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `integration_connector_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct IntegrationConnectorServiceCustom {
///     inner: Arc<IntegrationConnectorService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type IntegrationConnectorService = GenericCrudService<
    IntegrationConnector,
    CreateIntegrationConnectorDto,
    UpdateIntegrationConnectorDto,
    IntegrationConnectorRepository,
>;

// <<< CUSTOM
// END CUSTOM
