//! Application service for IntegrationEvent entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `integration_event_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateIntegrationEventDto, UpdateIntegrationEventDto};
use crate::domain::entity::IntegrationEvent;
use crate::infrastructure::persistence::IntegrationEventRepository;

/// Application service for IntegrationEvent entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `integration_event_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct IntegrationEventServiceCustom {
///     inner: Arc<IntegrationEventService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type IntegrationEventService = GenericCrudService<
    IntegrationEvent,
    CreateIntegrationEventDto,
    UpdateIntegrationEventDto,
    IntegrationEventRepository,
>;

// <<< CUSTOM
// END CUSTOM
