//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod integration_connector_service;
pub mod integration_event_service;

// <<< CUSTOM
pub mod integrations_ports;
pub mod integrations_events;
pub mod integrations_write_service;
pub mod integrations_oauth_ports;
pub mod integrations_oauth;
// END CUSTOM

pub use integration_connector_service::IntegrationConnectorService;
pub use integration_event_service::IntegrationEventService;
// <<< CUSTOM
pub use integrations_ports::{MapOutcome, MapRejected, MapRequest, MappedRef, TargetPort};
pub use integrations_events::{IntegrationEvent, IntegrationEventMapped, IntegrationEventSink, LoggingSink};
pub use integrations_write_service::{FailedEvent, InboundEvent, IntegrationError, IntegrationsWriteService, NewConnector, ReceiveOutcome};
pub use integrations_oauth_ports::{OAuthCredentialFailure, OAuthCredentialStore, PURPOSE_OAUTH_TOKEN, TokenBundle, TokenMetadata};
pub use integrations_oauth::{
    AccountStatus, AuthorizeRequest, AuthorizeResponse, CompleteOutcome, CompleteRequest,
    IntegrationsOauthConfig, IntegrationsOauthService, OauthError, RefreshSummary,
    STATE_TTL_SECONDS,
};
// END CUSTOM
