-- IntegrationEvent Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the integrations.integration_events table.
-- Customize this file to add your initial data.

-- INSERT INTO integrations.integration_events (
--     id,
--     company_id,
--     connector_id,
--     event_type,
--     external_id,
--     business_key,
--     status,
--     payload,
--     mapped_ref_type,
--     mapped_ref_id,
--     error_detail,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO integrations.integration_events (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

