-- Company RLS fence for integrations module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for integrations.integration_connectors
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE integrations.integration_connectors ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations.integration_connectors FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS integration_connectors_company_isolation ON integrations.integration_connectors;
CREATE POLICY integration_connectors_company_isolation ON integrations.integration_connectors
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for integrations.integration_events
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE integrations.integration_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations.integration_events FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS integration_events_company_isolation ON integrations.integration_events;
CREATE POLICY integration_events_company_isolation ON integrations.integration_events
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

