-- Migration: Create integration_events table
-- Generated by metaphor-schema

-- Create integration_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'integration_status') THEN
        CREATE TYPE integration_status AS ENUM ('received', 'mapped', 'ignored', 'failed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS integrations;

CREATE TABLE IF NOT EXISTS integrations.integration_events (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    connector_id UUID NOT NULL,
    event_type TEXT NOT NULL,
    external_id TEXT NOT NULL,
    business_key TEXT NOT NULL,
    status integration_status NOT NULL DEFAULT 'received',
    payload TEXT NOT NULL,
    mapped_ref_type TEXT,
    mapped_ref_id UUID,
    error_detail TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_integration_events_connector_id_business_key ON integrations.integration_events (connector_id, business_key);

CREATE INDEX IF NOT EXISTS idx_integration_events_company_id_status ON integrations.integration_events (company_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_integration_events_metadata_gin ON integrations.integration_events USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_integration_events_metadata_deleted_at ON integrations.integration_events ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_integration_events_metadata_created_at ON integrations.integration_events ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_integration_events_metadata_updated_at ON integrations.integration_events ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION integrations.integration_events_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS integration_events_insert_audit ON integrations.integration_events;
CREATE TRIGGER integration_events_insert_audit BEFORE INSERT ON integrations.integration_events
    FOR EACH ROW EXECUTE FUNCTION integrations.integration_events_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS integration_events_update_audit ON integrations.integration_events;
CREATE TRIGGER integration_events_update_audit BEFORE UPDATE ON integrations.integration_events
    FOR EACH ROW EXECUTE FUNCTION integrations.integration_events_audit_timestamp();
