-- Migration: Create integration_connectors table
-- Generated by metaphor-schema

-- Create connector_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'connector_kind') THEN
        CREATE TYPE connector_kind AS ENUM ('payment_gateway', 'marketplace', 'bank_feed', 'courier');
    END IF;
END
$$;

-- Create connector_direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'connector_direction') THEN
        CREATE TYPE connector_direction AS ENUM ('inbound', 'outbound', 'both');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS integrations;

CREATE TABLE IF NOT EXISTS integrations.integration_connectors (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    provider TEXT NOT NULL,
    kind connector_kind NOT NULL,
    direction connector_direction NOT NULL DEFAULT 'inbound',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_integration_connectors_company_id_provider ON integrations.integration_connectors (company_id, provider);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_integration_connectors_metadata_gin ON integrations.integration_connectors USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_integration_connectors_metadata_deleted_at ON integrations.integration_connectors ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_integration_connectors_metadata_created_at ON integrations.integration_connectors ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_integration_connectors_metadata_updated_at ON integrations.integration_connectors ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION integrations.integration_connectors_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS integration_connectors_insert_audit ON integrations.integration_connectors;
CREATE TRIGGER integration_connectors_insert_audit BEFORE INSERT ON integrations.integration_connectors
    FOR EACH ROW EXECUTE FUNCTION integrations.integration_connectors_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS integration_connectors_update_audit ON integrations.integration_connectors;
CREATE TRIGGER integration_connectors_update_audit BEFORE UPDATE ON integrations.integration_connectors
    FOR EACH ROW EXECUTE FUNCTION integrations.integration_connectors_audit_timestamp();
