-- Audit Triggers Migration for integrations module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: IntegrationConnector (integrations.integration_connectors)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION integrations.integration_connectors_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS integration_connectors_insert_audit ON integrations.integration_connectors;
CREATE TRIGGER integration_connectors_insert_audit BEFORE INSERT ON integrations.integration_connectors
    FOR EACH ROW EXECUTE FUNCTION integrations.integration_connectors_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS integration_connectors_update_audit ON integrations.integration_connectors;
CREATE TRIGGER integration_connectors_update_audit BEFORE UPDATE ON integrations.integration_connectors
    FOR EACH ROW EXECUTE FUNCTION integrations.integration_connectors_audit_timestamp();

-- ==============================================================================
-- Table: IntegrationEvent (integrations.integration_events)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION integrations.integration_events_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS integration_events_insert_audit ON integrations.integration_events;
CREATE TRIGGER integration_events_insert_audit BEFORE INSERT ON integrations.integration_events
    FOR EACH ROW EXECUTE FUNCTION integrations.integration_events_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS integration_events_update_audit ON integrations.integration_events;
CREATE TRIGGER integration_events_update_audit BEFORE UPDATE ON integrations.integration_events
    FOR EACH ROW EXECUTE FUNCTION integrations.integration_events_audit_timestamp();

