-- Migration: Create integration_accounts table
-- Generated by metaphor-schema

-- Create o_auth_provider enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'o_auth_provider') THEN
        CREATE TYPE o_auth_provider AS ENUM ('gmail', 'outlook', 'google_calendar', 'microsoft_calendar');
    END IF;
END
$$;

-- Create integration_account_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'integration_account_status') THEN
        CREATE TYPE integration_account_status AS ENUM ('pending', 'active', 'expired', 'revoked');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS integrations;

CREATE TABLE IF NOT EXISTS integrations.integration_accounts (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    provider o_auth_provider NOT NULL,
    account_ref TEXT NOT NULL,
    status integration_account_status NOT NULL DEFAULT 'pending',
    scopes TEXT NOT NULL DEFAULT '',
    pkce_verifier TEXT,
    expires_at TIMESTAMPTZ,
    last_refreshed_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_integration_accounts_company_id_provider_account_ref ON integrations.integration_accounts (company_id, provider, account_ref);

CREATE INDEX IF NOT EXISTS idx_integration_accounts_company_id_status ON integrations.integration_accounts (company_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_integration_accounts_metadata_gin ON integrations.integration_accounts USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_integration_accounts_metadata_deleted_at ON integrations.integration_accounts ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_integration_accounts_metadata_created_at ON integrations.integration_accounts ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_integration_accounts_metadata_updated_at ON integrations.integration_accounts ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION integrations.integration_accounts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS integration_accounts_insert_audit ON integrations.integration_accounts;
CREATE TRIGGER integration_accounts_insert_audit BEFORE INSERT ON integrations.integration_accounts
    FOR EACH ROW EXECUTE FUNCTION integrations.integration_accounts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS integration_accounts_update_audit ON integrations.integration_accounts;
CREATE TRIGGER integration_accounts_update_audit BEFORE UPDATE ON integrations.integration_accounts
    FOR EACH ROW EXECUTE FUNCTION integrations.integration_accounts_audit_timestamp();
