-- Enum types for integrations module
-- Generated by metaphor-schema

-- Create connector_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'connector_kind') THEN
        CREATE TYPE connector_kind AS ENUM ('payment_gateway', 'marketplace', 'bank_feed', 'courier');
    END IF;
END
$$;

-- Create connector_direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'connector_direction') THEN
        CREATE TYPE connector_direction AS ENUM ('inbound', 'outbound', 'both');
    END IF;
END
$$;

-- Create integration_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'integration_status') THEN
        CREATE TYPE integration_status AS ENUM ('received', 'mapped', 'ignored', 'failed');
    END IF;
END
$$;

