//! Event handler trait for IntegrationAccount events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::IntegrationAccountEvent;

/// Event handler for IntegrationAccount events.
/// Implement this trait to react to IntegrationAccount lifecycle events.
pub trait IntegrationAccountEventHandler: EventHandler<IntegrationAccountEvent> {}
