//! Domain events for IntegrationEvent entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::IntegrationEvent;

/// Domain events for IntegrationEvent — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<IntegrationEvent>)` variant.
pub type IntegrationEventEvent = CrudEvent<IntegrationEvent>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for IntegrationEvent events.
pub type IntegrationEventEventPublisher = Arc<dyn CrudEventPublisher<IntegrationEvent> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopIntegrationEventEventPublisher = NoOpCrudEventPublisher<IntegrationEvent>;
