//! Domain events for IntegrationConnector entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::IntegrationConnector;

/// Domain events for IntegrationConnector — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<IntegrationConnector>)` variant.
pub type IntegrationConnectorEvent = CrudEvent<IntegrationConnector>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for IntegrationConnector events.
pub type IntegrationConnectorEventPublisher = Arc<dyn CrudEventPublisher<IntegrationConnector> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopIntegrationConnectorEventPublisher = NoOpCrudEventPublisher<IntegrationConnector>;
