//! Event handler trait for IntegrationConnector events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::IntegrationConnectorEvent;

/// Event handler for IntegrationConnector events.
/// Implement this trait to react to IntegrationConnector lifecycle events.
pub trait IntegrationConnectorEventHandler: EventHandler<IntegrationConnectorEvent> {}
