//! Domain events for IntegrationAccount entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::IntegrationAccount;

/// Domain events for IntegrationAccount — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<IntegrationAccount>)` variant.
pub type IntegrationAccountEvent = CrudEvent<IntegrationAccount>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for IntegrationAccount events.
pub type IntegrationAccountEventPublisher = Arc<dyn CrudEventPublisher<IntegrationAccount> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopIntegrationAccountEventPublisher = NoOpCrudEventPublisher<IntegrationAccount>;
