//! Event handler trait for IntegrationEvent events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::IntegrationEventEvent;

/// Event handler for IntegrationEvent events.
/// Implement this trait to react to IntegrationEvent lifecycle events.
pub trait IntegrationEventEventHandler: EventHandler<IntegrationEventEvent> {}
