//! Event subscriber type aliases for Integrations module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::IntegrationConnectorEvent;
use crate::domain::event::IntegrationEventEvent;

/// Subscriber for IntegrationConnector events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type IntegrationConnectorEventSubscriber = GenericEventSubscriber<IntegrationConnectorEvent>;

/// Subscriber for IntegrationEvent events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type IntegrationEventEventSubscriber = GenericEventSubscriber<IntegrationEventEvent>;

// <<< CUSTOM
// END CUSTOM
