//! IntegrationConnector seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial IntegrationConnector data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// INTEGRATIONCONNECTOR SEEDER
// ============================================================================

/// Seeder for integration_connector
pub struct SeedIntegrationConnectorSeeder;

impl SeedIntegrationConnectorSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedIntegrationConnectorSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedIntegrationConnectorSeeder {
    fn name(&self) -> &'static str {
        "SeedIntegrationConnectorSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if integrations.integration_connectors table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM integrations.integration_connectors")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/integration_connector_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM integrations.integration_connectors")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
