//! Repository trait for IntegrationConnector aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the IntegrationConnector aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{IntegrationConnector, ConnectorDirection, ConnectorKind, ConnectorStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct IntegrationConnectorPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl IntegrationConnectorPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct IntegrationConnectorPaginatedResult {
    pub data: Vec<IntegrationConnector>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct IntegrationConnectorFilter {
    pub company_id: Option<Uuid>,
    pub provider: Option<String>,
    pub kind: Option<ConnectorKind>,
    pub direction: Option<ConnectorDirection>,
    pub status: Option<ConnectorStatus>,
}

impl IntegrationConnectorFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.provider.is_some() || self.kind.is_some() || self.direction.is_some() || self.status.is_some()
    }
}

/// Repository trait for IntegrationConnector aggregate
///
/// This trait defines the persistence contract for IntegrationConnector entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait IntegrationConnectorRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new integration_connector entity
    async fn save(&self, entity: &IntegrationConnector) -> Result<IntegrationConnector>;

    /// Find integration_connector by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<IntegrationConnector>>;

    /// Find all integration_connector entities
    async fn find_all(&self) -> Result<Vec<IntegrationConnector>>;

    /// Update integration_connector by ID
    async fn update(&self, id: &str, entity: &IntegrationConnector) -> Result<Option<IntegrationConnector>>;

    /// Delete integration_connector by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List integration_connector with pagination
    async fn list(&self, params: IntegrationConnectorPaginationParams) -> Result<IntegrationConnectorPaginatedResult>;

    /// List integration_connector with pagination and filters
    async fn list_with_filters(&self, params: IntegrationConnectorPaginationParams, filters: IntegrationConnectorFilter) -> Result<IntegrationConnectorPaginatedResult>;

    /// Count all integration_connector entities
    async fn count(&self) -> Result<u64>;

    /// Count integration_connector entities matching filters
    async fn count_with_filters(&self, filters: IntegrationConnectorFilter) -> Result<u64>;

    /// Check if integration_connector exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete integration_connector by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted integration_connector by ID
    async fn restore(&self, id: &str) -> Result<Option<IntegrationConnector>>;

    /// List soft-deleted integration_connector entities
    async fn list_deleted(&self, params: IntegrationConnectorPaginationParams) -> Result<IntegrationConnectorPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save integration_connector entities
    async fn bulk_save(&self, entities: &[IntegrationConnector]) -> Result<Vec<IntegrationConnector>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
