//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod integration_connector_repository;
pub mod integration_event_repository;

// Re-exports
pub use integration_connector_repository::{
    IntegrationConnectorRepository,
    IntegrationConnectorPaginationParams,
    IntegrationConnectorPaginatedResult,
    IntegrationConnectorFilter,
};
pub use integration_event_repository::{
    IntegrationEventRepository,
    IntegrationEventPaginationParams,
    IntegrationEventPaginatedResult,
    IntegrationEventFilter,
};
