//! Repository for IntegrationConnector entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written IntegrationConnector SQL — the registration and the reads that fence an
//! inbound webhook to the tenant owning the connector (4-layer rule: services orchestrate, repos hold
//! SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<IntegrationConnector, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::IntegrationConnector;

/// Table name for IntegrationConnector entities
pub const TABLE_NAME: &str = "integrations.integration_connectors";

/// Repository for IntegrationConnector entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct IntegrationConnectorRepository(
    backbone_orm::GenericCrudRepository<IntegrationConnector, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for IntegrationConnectorRepository {
    type Target = backbone_orm::GenericCrudRepository<IntegrationConnector, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl IntegrationConnectorRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a connector registration writes.
///
/// Mirrors the raw column shape rather than the `IntegrationConnector` entity: `is_active` is the
/// literal `true`, and `kind`/`direction` bind as `&str` with DB-side casts (`$4::connector_kind`,
/// `$5::connector_direction`) so an unknown value fails as a DB error rather than a deserialize panic.
pub struct NewConnectorRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub provider: &'a str,
    pub kind: &'a str,
    pub direction: &'a str,
}

/// What an inbound event needs to know about its connector before it is admitted.
pub struct ConnectorGateRow {
    pub kind: String,
    pub is_active: bool,
}

/// What a retry run needs: the connector's OWN company (the loop binds it explicitly) and its kind.
pub struct ConnectorRetryRow {
    pub company_id: Uuid,
    pub kind: String,
}

/// Hand-written IntegrationConnector SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl IntegrationConnectorRepository {
    /// Register a connector to an external provider.
    ///
    /// A write outside any transaction; the caller wraps it in `with_company_scope(Some(company_id))` —
    /// the company is on the DTO, and that scope satisfies the INSERT's WITH CHECK fence (ADR-0008).
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to turn
    /// a duplicate provider into a domain error.
    pub async fn insert_connector(
        &self,
        pool: &PgPool,
        c: &NewConnectorRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO integrations.integration_connectors
                     (id, company_id, provider, kind, direction, is_active)
                   VALUES ($1,$2,$3,$4::connector_kind,$5::connector_direction,true)"#,
            )
            .bind(c.id).bind(c.company_id).bind(c.provider).bind(c.kind).bind(c.direction),
        )
        .await?;
        Ok(())
    }

    /// Read the connector an inbound event names. `Ok(None)` = no such connector in scope.
    ///
    /// Runs outside a transaction on the pool; the caller wraps it in
    /// `with_company_scope(Some(company_id))` using the company named on the WEBHOOK payload — a
    /// provider callback has no ambient scope of its own, so the fence must be explicit (ADR-0008).
    pub async fn fetch_gate(
        &self,
        pool: &PgPool,
        connector_id: Uuid,
    ) -> Result<Option<ConnectorGateRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT kind::text AS kind, is_active FROM integrations.integration_connectors
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(connector_id),
        )
        .await?;
        Ok(row.map(|r| ConnectorGateRow { kind: r.get("kind"), is_active: r.get("is_active") }))
    }

    /// Read the connector a retry run re-drives, including its OWN company.
    ///
    /// ID-only: identified by the connector id alone, so this read rides the request-dedicated
    /// connection. The caller then carries the company it learns here explicitly onto every read/write
    /// in the retry loop — that loop is long-running and may outlive the request scope.
    pub async fn fetch_for_retry(
        &self,
        pool: &PgPool,
        connector_id: Uuid,
    ) -> Result<Option<ConnectorRetryRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                "SELECT company_id, kind::text AS kind FROM integrations.integration_connectors WHERE id=$1")
                .bind(connector_id),
        )
        .await?;
        Ok(row.map(|r| ConnectorRetryRow { company_id: r.get("company_id"), kind: r.get("kind") }))
    }
}

backbone_core::impl_crud_repository!(IntegrationConnectorRepository, IntegrationConnector, soft_delete);
