//! Repository for IntegrationEvent entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<IntegrationEvent, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::IntegrationEvent;

/// Table name for IntegrationEvent entities
pub const TABLE_NAME: &str = "integrations.integration_events";

/// Repository for IntegrationEvent entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct IntegrationEventRepository(
    backbone_orm::GenericCrudRepository<IntegrationEvent, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for IntegrationEventRepository {
    type Target = backbone_orm::GenericCrudRepository<IntegrationEvent, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl IntegrationEventRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(IntegrationEventRepository, IntegrationEvent, soft_delete);
