//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod integration_connector_repository;
mod integration_event_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use integration_connector_repository::IntegrationConnectorRepository;
pub use integration_event_repository::IntegrationEventRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// The hand-written integrations SQL's parameter/projection types (see
// `integration_connector_repository` and `integration_event_repository`, both declared `user_owned` in
// metaphor.codegen.yaml).
pub use integration_connector_repository::{ConnectorGateRow, ConnectorRetryRow, NewConnectorRow};
pub use integration_event_repository::{EventOutcomeRow, FailedEventRow, NewEventRow};
// END CUSTOM