//! Validator for IntegrationConnector entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<IntegrationConnector>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::IntegrationConnector;

/// Validator type alias for IntegrationConnector entities.
pub type IntegrationConnectorValidator = EntityValidator<IntegrationConnector>;

/// Build a validator for IntegrationConnector with all schema-defined field rules.
pub fn integration_connector_validator() -> IntegrationConnectorValidator {
    EntityValidator::new()
        .rule(RequiredString::new("provider", |e: &IntegrationConnector| &e.provider))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
