//! Validator for IntegrationAccount entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<IntegrationAccount>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::IntegrationAccount;

/// Validator type alias for IntegrationAccount entities.
pub type IntegrationAccountValidator = EntityValidator<IntegrationAccount>;

/// Build a validator for IntegrationAccount with all schema-defined field rules.
pub fn integration_account_validator() -> IntegrationAccountValidator {
    EntityValidator::new()
        .rule(RequiredString::new("account_ref", |e: &IntegrationAccount| &e.account_ref))
        .rule(RequiredString::new("scopes", |e: &IntegrationAccount| &e.scopes))
        .rule(OptionalNotBlank::new("pkce_verifier", |e: &IntegrationAccount| e.pkce_verifier.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
