//! Auth configuration for IntegrationEvent handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<IntegrationEvent>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::IntegrationEventService;
use crate::domain::entity::IntegrationEvent;

/// Permission string constants for IntegrationEvent operations.
pub mod permissions {
    pub const LIST:        &str = "integration_event:list";
    pub const READ:        &str = "integration_event:read";
    pub const CREATE:      &str = "integration_event:create";
    pub const UPDATE:      &str = "integration_event:update";
    pub const DELETE:      &str = "integration_event:delete";
    pub const RESTORE:     &str = "integration_event:restore";
    pub const TRASH:       &str = "integration_event:trash";
    pub const EMPTY_TRASH: &str = "integration_event:empty_trash";
    pub const BULK_CREATE: &str = "integration_event:bulk_create";
    pub const UPSERT:      &str = "integration_event:upsert";
}

/// Resource policy for IntegrationEvent — maps CRUD actions to permission strings.
pub struct IntegrationEventPolicy;

#[async_trait]
impl ResourcePolicy<IntegrationEvent> for IntegrationEventPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &IntegrationEvent,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for IntegrationEvent handlers.
///
/// Wraps `IntegrationEventService` and checks `IntegrationEventPolicy` before delegating.
pub type IntegrationEventGuard = PermissionGuard<IntegrationEvent>;

/// Service-integrated permission guard for IntegrationEvent (for use in generated handlers).
pub type IntegrationEventServiceGuard = ServicePermissionGuard<IntegrationEvent, IntegrationEventService, IntegrationEventPolicy>;

// <<< CUSTOM
// END CUSTOM
