//! Auth configuration for IntegrationConnector handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<IntegrationConnector>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::IntegrationConnectorService;
use crate::domain::entity::IntegrationConnector;

/// Permission string constants for IntegrationConnector operations.
pub mod permissions {
    pub const LIST:        &str = "integration_connector:list";
    pub const READ:        &str = "integration_connector:read";
    pub const CREATE:      &str = "integration_connector:create";
    pub const UPDATE:      &str = "integration_connector:update";
    pub const DELETE:      &str = "integration_connector:delete";
    pub const RESTORE:     &str = "integration_connector:restore";
    pub const TRASH:       &str = "integration_connector:trash";
    pub const EMPTY_TRASH: &str = "integration_connector:empty_trash";
    pub const BULK_CREATE: &str = "integration_connector:bulk_create";
    pub const UPSERT:      &str = "integration_connector:upsert";
}

/// Resource policy for IntegrationConnector — maps CRUD actions to permission strings.
pub struct IntegrationConnectorPolicy;

#[async_trait]
impl ResourcePolicy<IntegrationConnector> for IntegrationConnectorPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &IntegrationConnector,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for IntegrationConnector handlers.
///
/// Wraps `IntegrationConnectorService` and checks `IntegrationConnectorPolicy` before delegating.
pub type IntegrationConnectorGuard = PermissionGuard<IntegrationConnector>;

/// Service-integrated permission guard for IntegrationConnector (for use in generated handlers).
pub type IntegrationConnectorServiceGuard = ServicePermissionGuard<IntegrationConnector, IntegrationConnectorService, IntegrationConnectorPolicy>;

// <<< CUSTOM
// END CUSTOM
