//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod integration_connector_auth;
pub mod integration_event_auth;

pub use integration_connector_auth::{IntegrationConnectorPolicy, IntegrationConnectorGuard, IntegrationConnectorServiceGuard};
pub use integration_event_auth::{IntegrationEventPolicy, IntegrationEventGuard, IntegrationEventServiceGuard};

// <<< CUSTOM
// END CUSTOM
