//! IntegrationConnector API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the IntegrationConnector CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// INTEGRATIONCONNECTOR TEST DATA GENERATOR
// ============================================================================

/// Test data generator for IntegrationConnector
pub struct IntegrationConnectorTestData;

impl TestDataGenerator for IntegrationConnectorTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "provider": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "kind": "payment_gateway",
            "direction": "inbound",
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "provider": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "kind": "payment_gateway",
            "direction": "inbound",
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// INTEGRATIONCONNECTOR API TEST
// ============================================================================

/// IntegrationConnector API test suite
pub struct IntegrationConnectorApiTest {
    inner: GenericCrudTest<IntegrationConnectorTestData>,
}

impl IntegrationConnectorApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/integration_connectors", "IntegrationConnector");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, IntegrationConnectorTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for IntegrationConnectorApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_integration_connector_crud() {
        let mut test = IntegrationConnectorApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add IntegrationConnector specific tests here
// <<< CUSTOM TESTS END >>>
