//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod integration_connector_api_test;
pub mod integration_event_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use integration_connector_api_test::*;
pub use integration_event_api_test::*;
