//! Integrations Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Integrations exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use integrations::exports::{IntegrationConnectorDto, IntegrationsQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `IntegrationConnectorDto` - Data transfer object for IntegrationConnector
/// - `IntegrationConnectorSummary` - Summary view of IntegrationConnector
/// - `IntegrationConnectorId` - Type-safe ID wrapper
/// - `IntegrationEventDto` - Data transfer object for IntegrationEvent
/// - `IntegrationEventSummary` - Summary view of IntegrationEvent
/// - `IntegrationEventId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `IntegrationsQueryService` - Read-only queries
///
/// ## Public Events
/// - `IntegrationConnectorCreatedEvent` - Published when IntegrationConnector is created
/// - `IntegrationConnectorUpdatedEvent` - Published when IntegrationConnector is updated
/// - `IntegrationConnectorDeletedEvent` - Published when IntegrationConnector is deleted
/// - `IntegrationEventCreatedEvent` - Published when IntegrationEvent is created
/// - `IntegrationEventUpdatedEvent` - Published when IntegrationEvent is updated
/// - `IntegrationEventDeletedEvent` - Published when IntegrationEvent is deleted
pub struct ExportSummary;
