//! Use case type aliases for IntegrationConnector aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateIntegrationConnectorDto, UpdateIntegrationConnectorDto};
use crate::application::service::IntegrationConnectorService;
use crate::domain::entity::IntegrationConnector;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateIntegrationConnectorUseCase = CreateUseCase<IntegrationConnector, CreateIntegrationConnectorDto, IntegrationConnectorService>;
pub type UpdateIntegrationConnectorUseCase = UpdateUseCase<IntegrationConnector, UpdateIntegrationConnectorDto, IntegrationConnectorService>;
pub type GetIntegrationConnectorUseCase    = GetUseCase<IntegrationConnector, IntegrationConnectorService>;
pub type DeleteIntegrationConnectorUseCase = DeleteUseCase<IntegrationConnector, IntegrationConnectorService>;
pub type ListIntegrationConnectorUseCase   = ListUseCase<IntegrationConnector, IntegrationConnectorService>;

// <<< CUSTOM
// END CUSTOM
