//! Use case type aliases for IntegrationEvent aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateIntegrationEventDto, UpdateIntegrationEventDto};
use crate::application::service::IntegrationEventService;
use crate::domain::entity::IntegrationEvent;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateIntegrationEventUseCase = CreateUseCase<IntegrationEvent, CreateIntegrationEventDto, IntegrationEventService>;
pub type UpdateIntegrationEventUseCase = UpdateUseCase<IntegrationEvent, UpdateIntegrationEventDto, IntegrationEventService>;
pub type GetIntegrationEventUseCase    = GetUseCase<IntegrationEvent, IntegrationEventService>;
pub type DeleteIntegrationEventUseCase = DeleteUseCase<IntegrationEvent, IntegrationEventService>;
pub type ListIntegrationEventUseCase   = ListUseCase<IntegrationEvent, IntegrationEventService>;

// <<< CUSTOM
// END CUSTOM
