//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod integration_connector_usecases;
pub mod integration_event_usecases;

pub use integration_connector_usecases::{
    CreateIntegrationConnectorUseCase, UpdateIntegrationConnectorUseCase, GetIntegrationConnectorUseCase,
    DeleteIntegrationConnectorUseCase, ListIntegrationConnectorUseCase,
};
pub use integration_event_usecases::{
    CreateIntegrationEventUseCase, UpdateIntegrationEventUseCase, GetIntegrationEventUseCase,
    DeleteIntegrationEventUseCase, ListIntegrationEventUseCase,
};

// <<< CUSTOM
// END CUSTOM
